export interface CollegeDbEntry {
  id: string
  name: string
  code: string
  /** Approximate overall undergraduate acceptance rate (0-100). Illustrative
   * figures from general knowledge of recent admissions cycles, not a live
   * or certified data feed - good enough to anchor a demo forecast, not to
   * cite as an official statistic. Where a school also appears in
   * lib/school-admissions-data.ts, that file's IPEDS-checked figure is the
   * one shown in the UI. */
  acceptanceRate: number
  /** US News 2026 National Universities rank, where the school is in that
   * ranking. Liberal arts colleges are ranked on a separate US News list and
   * carry no rank here - their absence is not a low placement. */
  usNewsRank?: number
}

// The US News 2026 top 150 National Universities, plus the liberal arts
// colleges this app already covered. US News ranks those on a separate list,
// so cutting to "top 150" alone would have dropped Williams, Amherst,
// Swarthmore, Pomona and Wellesley - schools a large share of applicants here
// actually apply to.
//
// Institution names are public facts, not creative content. Codes are stable
// placeholder IDs generated for this demo (not real CEEB/Common App codes) -
// swap in a real institution directory when this ships for real.
const NAMES_WITH_RATES: [name: string, acceptanceRate: number, usNewsRank?: number][] = [
  ['American University', 58, 88],
  ['Amherst College', 7],
  ['Arizona State University', 88, 117],
  ['Auburn University', 44, 102],
  ['Baylor University', 45, 88],
  ['Berea College', 32],
  ['Binghamton University', 44, 73],
  ['Boston College', 19, 36],
  ['Boston University', 14, 42],
  ['Bowdoin College', 9],
  ['Brandeis University', 35, 69],
  ['Brigham Young University', 67, 110],
  ['Brown University', 5, 13],
  ['Bryn Mawr College', 30],
  ['Bucknell University', 28],
  ['CUNY City College', 68, 132],
  ['California Institute of Technology', 3, 11],
  ['California State University, Fullerton', 63, 139],
  ['California State University, Long Beach', 43, 127],
  ['Carleton College', 14],
  ['Carnegie Mellon University', 11, 20],
  ['Case Western Reserve University', 30, 51],
  ['Chapman University', 66, 110],
  ['Claremont McKenna College', 9],
  ['Clark University', 72, 132],
  ['Clarkson University', 84, 143],
  ['Clemson University', 40, 75],
  ['Colby College', 8],
  ['Colgate University', 10],
  ['College of William & Mary', 33, 51],
  ['Colorado College', 12],
  ['Colorado School of Mines', 60, 80],
  ['Columbia University', 4, 15],
  ['Cornell University', 8, 12],
  ['Creighton University', 77, 117],
  ['Dartmouth College', 6, 13],
  ['Davidson College', 15],
  ['DePaul University', 68],
  ['Denison University', 30],
  ['Drexel University', 75, 80],
  ['Duke University', 6, 7],
  ['Elon University', 78, 117],
  ['Emory University', 11, 24],
  ['Fairfield University', 60, 139],
  ['Florida International University', 64, 97],
  ['Florida State University', 25, 51],
  ['Fordham University', 45, 97],
  ['George Mason University', 90, 117],
  ['George Washington University', 44, 59],
  ['Georgetown University', 12, 24],
  ['Georgia Institute of Technology', 15, 32],
  ['Gettysburg College', 44],
  ['Gonzaga University', 77, 102],
  ['Grinnell College', 9],
  ['Hamilton College', 11],
  ['Harvard University', 3, 3],
  ['Harvey Mudd College', 10],
  ['Haverford College', 14],
  ['Howard University', 35, 88],
  ['Illinois Institute of Technology', 61, 117],
  ['Indiana University Bloomington', 80, 73],
  ['Iowa State University', 90, 117],
  ['Johns Hopkins University', 7, 7],
  ['Kenyon College', 30],
  ['Lafayette College', 24],
  ['Lehigh University', 32, 46],
  ['Loyola Marymount University', 79, 102],
  ['Loyola University Chicago', 82, 132],
  ['Macalester College', 26],
  ['Marquette University', 83, 88],
  ['Massachusetts Institute of Technology', 4, 2],
  ['Miami University', 85, 143],
  ['Michigan State University', 85, 64],
  ['Middlebury College', 13],
  ['New Jersey Institute of Technology', 72, 80],
  ['New York University', 9, 32],
  ['North Carolina State University', 45, 64],
  ['Northeastern University', 7, 46],
  ['Northwestern University', 7, 7],
  ['Oberlin College', 30],
  ['Occidental College', 35],
  ['Ohio State University', 53, 41],
  ['Oregon State University', 83, 143],
  ['Pennsylvania State University', 50, 59],
  ['Pepperdine University', 33, 84],
  ['Pitzer College', 15],
  ['Pomona College', 6],
  ['Princeton University', 4, 1],
  ['Purdue University', 53, 46],
  ['Rensselaer Polytechnic Institute', 65, 64],
  ['Rice University', 9, 17],
  ['Rochester Institute of Technology', 66, 88],
  ['Rutgers University', 62, 42],
  ['Rutgers University, Camden', 77, 97],
  ['Rutgers University, Newark', 72, 75],
  ['Saint Louis University', 81, 102],
  ['San Diego State University', 39, 117],
  ['Santa Clara University', 50, 59],
  ['Scripps College', 30],
  ['Smith College', 30],
  ['Southern Methodist University', 48, 88],
  ['Stanford University', 4, 4],
  ['Stevens Institute of Technology', 46, 80],
  ['Stony Brook University', 49, 59],
  ['Swarthmore College', 7],
  ['Syracuse University', 55, 75],
  ['Temple University', 80, 102],
  ['Texas A&M University', 63, 51],
  ['Texas Christian University', 52, 97],
  ['Thomas Jefferson University', 78, 132],
  ['Touro University', 73, 143],
  ['Trinity College', 30],
  ['Tufts University', 9, 36],
  ['Tulane University', 11, 69],
  ['Union College', 35],
  ['University at Albany', 75, 127],
  ['University at Buffalo', 68, 75],
  ['University of Alabama at Birmingham', 87, 132],
  ['University of Arizona', 87, 127],
  ['University of California, Berkeley', 11, 15],
  ['University of California, Davis', 37, 32],
  ['University of California, Irvine', 21, 32],
  ['University of California, Los Angeles', 9, 17],
  ['University of California, Merced', 92, 57],
  ['University of California, Riverside', 78, 75],
  ['University of California, San Diego', 24, 29],
  ['University of California, Santa Barbara', 26, 40],
  ['University of California, Santa Cruz', 58, 88],
  ['University of Central Florida', 41, 117],
  ['University of Chicago', 5, 6],
  ['University of Colorado Boulder', 78, 97],
  ['University of Connecticut', 55, 69],
  ['University of Dayton', 78, 143],
  ['University of Delaware', 70, 88],
  ['University of Denver', 78, 117],
  ['University of Florida', 23, 30],
  ['University of Georgia', 40, 46],
  ['University of Houston', 70, 132],
  ['University of Illinois Chicago', 80, 84],
  ['University of Illinois Urbana-Champaign', 44, 36],
  ['University of Iowa', 86, 102],
  ['University of Kansas', 88, 143],
  ['University of Kentucky', 95, 143],
  ['University of Maryland Baltimore County', 78, 127],
  ['University of Maryland, College Park', 44, 42],
  ['University of Massachusetts Amherst', 57, 64],
  ['University of Miami', 19, 64],
  ['University of Michigan', 18, 20],
  ['University of Minnesota Twin Cities', 70, 59],
  ['University of Missouri', 79, 102],
  ['University of New Hampshire', 87, 117],
  ['University of North Carolina at Chapel Hill', 17, 26],
  ['University of North Carolina at Charlotte', 80, 143],
  ['University of Notre Dame', 13, 20],
  ['University of Oklahoma', 73, 110],
  ['University of Oregon', 85, 110],
  ['University of Pennsylvania', 6, 7],
  ['University of Pittsburgh', 50, 69],
  ['University of Richmond', 26],
  ['University of Rochester', 40, 46],
  ['University of San Diego', 56, 110],
  ['University of San Francisco', 72, 110],
  ['University of South Carolina', 64, 127],
  ['University of South Florida', 44, 88],
  ['University of Southern California', 10, 28],
  ['University of Tennessee, Knoxville', 47, 102],
  ['University of Texas at Austin', 29, 30],
  ['University of Texas at Dallas', 85, 110],
  ['University of Vermont', 64, 132],
  ['University of Virginia', 19, 26],
  ['University of Washington', 44, 42],
  ['University of Wisconsin-Madison', 43, 36],
  ['University of the Pacific', 78, 139],
  ['Vanderbilt University', 5, 17],
  ['Vassar College', 19],
  ['Villanova University', 24, 57],
  ['Virginia Commonwealth University', 91, 139],
  ['Virginia Tech', 56, 51],
  ['Wake Forest University', 22, 51],
  ['Washington University in St. Louis', 11, 20],
  ['Washington and Lee University', 15],
  ['Wellesley College', 13],
  ['Wesleyan University', 14],
  ['Wheaton College', 78],
  ['Whitman College', 50],
  ['Williams College', 8],
  ['Worcester Polytechnic Institute', 56, 84],
  ['Yale University', 4, 4],
  ['Yeshiva University', 62, 84],
]

function codeFor(name: string, index: number): string {
  let hash = 0
  for (let i = 0; i < name.length; i++) {
    hash = (hash * 31 + name.charCodeAt(i)) >>> 0
  }
  return String(1000 + ((hash + index * 7) % 9000)).padStart(4, '0')
}

export const COLLEGES_DATABASE: CollegeDbEntry[] = [...NAMES_WITH_RATES]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([name, acceptanceRate, usNewsRank], i) => ({
    id: `college-${i}`,
    name,
    code: codeFor(name, i),
    acceptanceRate,
    usNewsRank,
  }))
